data:
    dataset_factory: ImageDatasetWithOccupancyLabels
    n_points_in_mesh: 10000
    n_points_on_mesh: 1000
    equal: true
    n_primitives: 6
    normalize: false
    random_view: false
    dataset_directory: "/media/paschalidoud/MyData/onet_data/Humans/D-FAUST/"
    splits_file: "../config/d-faust_splits.csv"
    dataset_type: "dynamic_faust"
    mesh_folder: "mesh_seq_2"
    points_folder: "points_seq_2"
    surface_points_folder: "surface_points_seq_2"
    renderings_folder: "renderings-downsampled_2"

feature_extractor:
    type: resnet18
    freeze_bn: true
primitive_network: space_partitioner
structure_layer:
    - translations:att_translation
    - constant:sq
    - probs:all_ones
    - sharpness:constant_sharpness
primitive_layer:
    - shapes:att_sq
    - sizes:att_size
    - translations:att_translation
    - rotations:att_rotation
    - qos:att_qos
    - probs:all_ones
    - sharpness:constant_sharpness
loss_type: cluster_coverage
loss:
    sharpness: 10.0
    epochs: 1500
    steps_per_epoch: 500
    lr: 0.0001
